### PR TITLE
Fixed #33: Added orientation property to ImageProperties

### LINKED ISSUE #33: getImageProperties should include image rotation
My use case is to store an image in portrait mode with a certain aspect ratio and size. I noticed that on Android, `getImageProperties` does not work as expected for pictures taken in portrait mode. If the image is in portrait mode, I need to crop it in order to get the desired aspect ratio. For images taken with the built-in camera in portrait mode, `getImageProperties` returns the size as if the image was in landscape mode. In order to process this case correctly, I need to know the rotation of the image. `ImageProperties` would be the appropriate place to add the rotation attribute.

### PR DESCRIPTION
**Pull request by aryzhov**
Obtaining image orientation from EXIF header on Android. Setting orientation to Undefined on iOS, since EXIF API is deprecated and since image orientation on the images stored in Photos is always normal.

### CODE REVIEW

File: android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java [hunk 1]
```diff
@@ -105,10 +105,17 @@ public void onMethodCall(MethodCall call, Result result) {
...
       BitmapFactory.decodeFile(fileName,options);
-
       HashMap<String, Integer> properties = new HashMap<String, Integer>();
-      properties.put("width",options.outWidth);
-      properties.put("height",options.outHeight);
+      properties.put("width", options.outWidth);
+      properties.put("height", options.outHeight);
+
+      try {
+        ExifInterface exif = new ExifInterface(fileName);
```
Comment (btastic) [inline android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java]: nitpick: I don't like that everything is inside this try/catch block. It would be good that only code that can fail will be handled. I don't know what could fail, but I'd do something like this:

```java
int orientation = 0;
properties.put("orientation", orientation);

ExifInterface exif = null;

try {
  // assuming this can throw an exception
  exif = new ExifInterface(fileName);  
} catch (IOException ex)
  // why can this happen?
}

if(exif != null) {
  orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_UNDEFINED);
  properties.put("orientation", orientation);
}
```

**Comment by aryzhov** [comment]
I agree withe your try .. catch block comment. I'll make the change and submit it after testing.

**Comment by btastic** [comment]
Thank you!
